// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChgxTrslce6fIcop4QXMzbwxjNsAq5lx4',
    appId: '1:831579308658:web:9b79d658cafd919529b8eb',
    messagingSenderId: '831579308658',
    projectId: 'streens-cec74',
    authDomain: 'streens-cec74.firebaseapp.com',
    storageBucket: 'streens-cec74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD1FvNgASnSGVlbe4qqsHFKcHhWr_E2tw',
    appId: '1:831579308658:android:ad88406373e577e529b8eb',
    messagingSenderId: '831579308658',
    projectId: 'streens-cec74',
    storageBucket: 'streens-cec74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSttgQXRlGDBApR9nhJlPoY70-Ga0iRpU',
    appId: '1:831579308658:ios:01090a8c50236f3829b8eb',
    messagingSenderId: '831579308658',
    projectId: 'streens-cec74',
    storageBucket: 'streens-cec74.firebasestorage.app',
    androidClientId: '831579308658-j2m2b2fihn36hpk8n75hromhvlqui7sd.apps.googleusercontent.com',
    iosClientId: '831579308658-h42l9dq0huouqkbm5qdgr03hi8ruqtfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitbit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSttgQXRlGDBApR9nhJlPoY70-Ga0iRpU',
    appId: '1:831579308658:ios:01090a8c50236f3829b8eb',
    messagingSenderId: '831579308658',
    projectId: 'streens-cec74',
    storageBucket: 'streens-cec74.firebasestorage.app',
    androidClientId: '831579308658-j2m2b2fihn36hpk8n75hromhvlqui7sd.apps.googleusercontent.com',
    iosClientId: '831579308658-h42l9dq0huouqkbm5qdgr03hi8ruqtfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitbit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChgxTrslce6fIcop4QXMzbwxjNsAq5lx4',
    appId: '1:831579308658:web:2be17dfc51404fa429b8eb',
    messagingSenderId: '831579308658',
    projectId: 'streens-cec74',
    authDomain: 'streens-cec74.firebaseapp.com',
    storageBucket: 'streens-cec74.firebasestorage.app',
  );
}
